version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: register_postgres
    ports:
      - '7500:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: register_redis
    ports:
      - '7379:6379'
    volumes:
      - redisDB:/data
volumes:
  redisDB:
  postgres:
